# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 643fc10313610bdfee249332eb47018547ad6b37d6b5031f640815a1591f8077b188aa213ae495cd9ba5abfbd00449ea0b0c167f88ddadb57e742800d84ac0fd

test:
  secret_key_base: 6f33c5abce246a0e75cb9403e26c3360613c71c6576d3cfc35f953d4dad508587173fe690493ecaa9d9e8dbb1faa0f538f01a1094efc86d252e40314409fc7db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
